### ISSUE TITLE
Split temperatureDivisor  

### ISSUE THREAD

**Issue by itai25** [iRayanKhan/homebridge-tuya#246]
**Checklist**
- [x] I have read the common issues wiki page
- [x] I have checked to make sure the plugin is up to date

**Describe the bug**
Currently temperatureDivisor divides both DesiredTemperature and CurrentTemperature, my device uses two numbers for desired (e.g 24) so I don't need to divide it and three numbers for current temperature (e.g 235) so I need to divide it by 10.
Could you please split temperatureDivisor into DesiredtemperatureDivisor and CurrenttemperatureDivisor?

**Environment (please complete the following information):**
 - OS: macOS Catalina
-  iOS version: 14.4.2
-  Homehubs: Hoobs 3.3.5
 - Node Version: 14.16.0
 - Plugin Version: 2.0.1
-  Accessory Type: SimpleHeater

**Comment by itai25** [comment]
Resolves #125 as well.

**Comment by markbegma** [comment]
I have exactly the same issue. On my thermostat response data target temperature is fetched correctly, but current temperature is scaled tenfold, so common divisor ruins one of them in any case.

**Comment by markbegma** [comment]
It seems to me that for each registered devise `context` var includes the entire jsonconfig as well, so it would suffice to repurpose temperatureDivisor to only function for current temperature, and create other variables for target and threshold temps by adding

`"targetTemperatureDivisor": {
                "type": "integer",
                "placeholder": "1",
                "condition": {
                  "functionBody": "return model.devices && model.devices[arrayIndices] && ['SimpleHeater'].includes(model.devices[arrayIndices].type);"
                }
              },
"thresholdTemperatureDivisor": {
                "type": "integer",
                "placeholder": "1",
                "condition": {
                  "functionBody": "return model.devices && model.devices[arrayIndices] && ['SimpleHeater'].includes(model.devices[arrayIndices].type);"
                }
              },`

at line 409 of config.schema.json

and 

`this.targetTemperatureDivisor = parseInt(this.device.context.temperatureDivisor) || 1;
this.thresholdTemperatureDivisor = parseInt(this.device.context.temperatureDivisor) || 1;`
at line 29, change lines 60-61 to
`.updateValue(this._getDividedState(dps[this.dpDesiredTemperature], this.thresholdTemperatureDivisor))
            .on('get', this.getDividedState.bind(this, this.dpDesiredTemperature, this.thresholdTemperatureDivisor))`
and change line 76 to
`characteristicHeatingThresholdTemperature.updateValue(changes[this.dpDesiredTemperature * this.temperatureDivisor])`
in SimpleHeaterAccessory.js

Can we maybe try this kind of quickfix in the next beta? I really don't want to fork just because of this...

**Comment by markbegma** [comment]
Tested on my fork, seems to have fixed it. Added a pull request #251

**Comment by paqpaqpaq** [comment]
@iRayanKhan 
As for current temperature divisor only, how can I handle this?
If I set Temperaturedivisor to 10, Current temp goes to (aimed) /10, but the desiredtemperature goes x10
Regardless what I try afterwards, e.g. ALSO specify targettemperaturedivisor 10, it remains tenfold.

@markbegma How did you solve this, since you had the exact same issue to begin with.
